<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>_00_device_report</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\common\Common.fs" Link="Common.fs" />
    <Compile Include="..\common\TaskRunners.fs" Link="TaskRunners.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Brahma.FSharp" Version="2.0.6" />
  </ItemGroup>

</Project>
